# Generated by Django 4.0.5 on 2022-06-02 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='courseId',
        ),
    ]
