# Generated by Django 4.0.5 on 2022-06-02 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_remove_syllabus_courseid'),
        ('course', '0004_coursesyllabusmapping'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursesyllabusmapping',
            unique_together={('courseId', 'syllabusId')},
        ),
    ]
