# Generated by Django 4.0.5 on 2022-06-02 03:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0004_coursesyllabusmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('enrollmentId', models.UUIDField(default=uuid.UUID('4025d9bd-9261-4871-815b-9dd775fea458'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('courseSyllabusMapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursesyllabusmapping')),
            ],
        ),
    ]
